# ---------------------------------------------------------------
# Jekyll & Global Configuration
## Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site settings
title: 喵窝
email: ruoyinyun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  每天都在努力变成更好的自己
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Vanny

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
